export const test="Test jest robiony w różnych odstępach czasy, aby sprawdzić aktualne mozliwości kolarza. Dane te są potrzebne dla kolarza aby okreslić maksymalne tempo jakie jest w stanie utrzymać prze pół godziny i na tej podstawie określić poziom intensywności przy konkretnych treningach. Test powinien być przeprowadzony możliwie zawsze w takich samych warunkach, najlepiej przypominających, te które będą obowiązywały podczas maratonu. Poziom intensywności jest tu maksymalnu możliwy."

export const regeneration="Celem tego treningu jest aktywna regeneracja mieśni. Jest udowodnione, że przy niskiej intensywności treningu regeneracyjnego mieśnie otrzymuja dodatkowego impulsu do regenerecji, stąd postepuje ona szybciej. Niemniej jednak, trzeba pamietać o tym, żeby nie przekroczyć progu niskiej intensywności, ani nie przesadzać z dłygością treningu - standardowo dla ultramaratonistów jest to ok 20-40km. Grozi to utratą dnia regenarycyjnego i zmęczenia podczas nastepnego dnia treningowego. Poziom intensywności oparty na własnych odczuciach, w porównaniu z testem, w skali 1-10: 2-4"

export const aerobicEndurance="W przypadku ultramaratonów jest to jeden z najważniejszych treningów. Jego celem jest stopniowe przywyczajanie organizmu do dłuższego wysiłku na rowerze. Osiągnietę to może być poprzez dłuższy trening stanowiący 20-60% czasu, który spędzimy podczes ultranamatonu, przy jednoczesnym niewielkim zwiększeniu intensywności treningu w porównaniu z planowaną średnią intensywnością podczas maratonu. Poziom intensywności oparty na własnych odczuciach, w porównaniu z testem, w skali 1-10: 5.5-6.5"

export const strenghtAndSpeed="W przypadku ultramaratonów treningi siłowe i szybkościowe są szczególnie ważne w okresie podstawowym, ponieważ dzięki nim można zbudować bazę na podstawie, ktorej możemy w późniejszym okresie rozwijać umiejetności, które nas interesują. W opisie treningu siłowego pierwsza liczba to ilośc serii, druga to ilość powtórzeń, a przedział informuje o tym ile ma byc obrotów korbą podczas jednego powtórzenia. Przerwy miedzy seriami to 3-5 min a miedzy powtórzeniami to 1-3min. W opisie treningu szybkościowego pierszali liczba to ilośc serii, druga to ilośc powtórzeń a trzecia to ilośc minut na każde powtórzenie. Przerwy miedzy seriami to 4-7 min a miedzy powtórzeniami to 1-3 min. Poziom intensywności oparty na własnych odczuciach, w porównaniu z testem, w skali 1-10: 7-10"

export const strenghtEndurance="Jest to bardzo ważny trening w okresie rozbudowy, ponieważ pozwala na zwikszenie mocy podczas dłuższych jazd, co jest szczególnie ważne w kontekscie podjazdów utrzymania wysokiego tempa. Trening zakłada dłuższe interwały w zalezności i etapu przygotowania. Najcześciej w przypadku ultramaratonów sa to dwa dłuższe interwały, ale moga to być trzy albo cztery krótsze. Poziom intensywności oparty na własnych odczuciach, w porównaniu z testem, w skali 1-10: 7-9"

export const dayOff="Nawet najwięksi profesionaliści muszą kiedyś opdpocząć, dlatego przynajmniej jeden dzień w tygodniu powinno się spedzić na odpoczynku. Bardzo ważne jest, żeby nie zapomniec o dniu wolnym, poniewąz może on się okazać niezbedny, żeby uniknąć przeprenowania i kontuzji"

export const marathonSimulation="Chyba nie trzeba przekonywać jak ważne jest żeby wiedzieć na jaki wysiłek się porywamy. W zdobyciu tej wiedzy najlepsza jest wymulacja maratonu. Symulacja dystansu nie musi i w wiekszości nie odnosi sie do pełnego dystancu. Może to być ok. 60-85% dystansu maratonu. Kluczem jest tu jak najbliższa imitacja maratonu czyli: trasa, warunki atmosferyczne, pora dnia, odżywianie, regeneracja przed symulacją itp. Poziom intensywności oparty na własnych odczuciach, w porównaniu z testem, w skali 1-10: 5-6"

export const dayOffOrRegeneration="Czasami zdarza się taka sytuacja, że nie wiemy czy wsiaść na rower czy może odpoczać. Wbrew temu co się wydaje, nie ma na to łatwej odpowiedzi i w głównej mierze zależy od odczuć i poziomu wytrenowania. Otóż to zawodnik musi zdecydować czy potrzebuje odpoczynku. Musi odróżnicz czy jestem przemeczony czy zwyczajnie mu sie nie chce wsiaść na rower. Poza tym, trzeba pamietać, że początkujący rowerzyści (bez wzgledu na to jak utalentowani) potrzebują tego odpoczynku wiecej niż ci bardziej doświadczeni"
